function renderActive(){
  const container=
    document.getElementById(
      'activeFilters'
    );

  container.innerHTML='';

  let count=0;


  function addFilterButton({
    kind,
    source,
    field=null,
    label
  }){
    const button=
      document.createElement(
        'button'
      );

    button.type='button';

    button.className=
      'active-filter-action';

    button.setAttribute(
      'aria-label',
      `Remove filter ${label}`
    );


    const labelElement=
      document.createElement(
        'span'
      );

    labelElement.className=
      'active-filter-action-label';

    labelElement.textContent=
      label;


    const removeOverlay=
      document.createElement(
        'span'
      );

    removeOverlay.className=
      'active-filter-action-remove';

    removeOverlay.textContent=
      'Remove filter';


    button.append(
      labelElement,
      removeOverlay
    );


    button.addEventListener(
      'click',
      event=>{
        event.preventDefault();
        event.stopPropagation();

        clearAppliedFilter({
          kind,
          source,
          field
        });
      }
    );


    container.appendChild(
      button
    );

    count++;
  }


  /*
   * Dropdown filters
   */
  Object.entries(
    dropdownState
  ).forEach(
    ([field,value])=>{

      if(value==='all'){
        return;
      }

      addFilterButton({
        kind:'dropdown',
        source:field,
        field,
        label:
          `${field}: ${value}`
      });
    }
  );


  /*
   * Plot-created filters.
   *
   * Each field gets its own removable Active Filters chip.
   * This is especially useful for compound filters such as a
   * heatmap selection containing both department and year.
   */
  Object.entries(
    plotFilters
  ).forEach(
    ([source,filters])=>{

      Object.entries(
        filters
      ).forEach(
        ([field,value])=>{

          const displayValue=
            field==='ids'
              ?`${value.length} selected`
              :value;

          addFilterButton({
            kind:'plot',
            source,
            field,
            label:
              `${source}: ${displayValue}`
          });
        }
      );
    }
  );


  if(!count){
    const empty=
      document.createElement(
        'span'
      );

    empty.className=
      'no-filter';

    empty.textContent=
      'No filters applied';

    container.appendChild(
      empty
    );
  }
}


function clearAppliedFilter(filter){

  /*
   * Dropdown filter
   */
  if(filter.kind==='dropdown'){

    dropdownState[
      filter.source
    ]='all';


    removeFilterFromRecency(
      'dropdown',
      filter.source
    );


    const select=
      document.getElementById(
        `filter-${filter.source}`
      );


    if(select){
      select.value='all';
    }

  }


  /*
   * Plot-generated filter
   */
  else if(
    filter.kind==='plot'
  ){

    const sourceFilters=
      plotFilters[
        filter.source
      ];


    /*
     * Active Filters & Actions passes a specific field.
     *
     * Remove only that field from a compound plot filter.
     * Example:
     *
     * heatmap = {
     *   department: "Public Health",
     *   year: 2025
     * }
     *
     * Clicking the year chip removes only year while keeping
     * department active.
     */
    if(
      filter.field &&
      sourceFilters &&
      Object.prototype
        .hasOwnProperty
        .call(
          sourceFilters,
          filter.field
        )
    ){

      delete sourceFilters[
        filter.field
      ];


      /*
       * Once no components remain, the originating plot filter
       * is no longer active and should leave the recency stack.
       */
      if(
        Object.keys(
          sourceFilters
        ).length===0
      ){

        removeFilterFromRecency(
          'plot',
          filter.source
        );

      }

    }


    /*
     * The filters displayed on each plot are grouped by source
     * and do not pass a field. Preserve their existing behavior:
     * clicking one clears the complete filter generated by that
     * plot.
     */
    else{

      plotFilters[
        filter.source
      ]={};


      removeFilterFromRecency(
        'plot',
        filter.source
      );

    }

  }


  renderDashboard();
}
